### ISSUE TITLE
关于remove方法的一些疑问

### ISSUE THREAD

**Issue by NoRomantic** [YueGod/simple_hashmap#1]
![微信图片_20200924161621](https://user-images.githubusercontent.com/38095225/94119378-6e1f4200-fe81-11ea-9585-46b5aee1d79d.png)

你好，这里remove方法的最后一个for循环我不是很理解为什么要从next开始判断。第一个元素不可能是需要删除的吗？

**Comment by NoRomantic** [comment]
我测试了一下，这边有个bug好像。当要删除的元素是链表的第一个元素是会报错，所以还需要加一个逻辑来处理第一个元素的情况。

**Comment by YueGod** [comment]
感谢反馈~当初只是为了写博客让人能够理解HashMap的实现。没有太仔细测过BUG，有时间我就修改一下~
